language: node_js

services: postgres

addons:
  ssh_known_hosts: greyjcr.com

before_script:
  - psql -c 'CREATE DATABASE "grey-test";' -U postgres
  - bash ./scripts/run-migrations.sh

before_deploy:
  - npm pack
  - mv grey-jcr-*.tgz grey-jcr.tgz

  - openssl aes-256-cbc -K $encrypted_ba634219ae9c_key -iv $encrypted_ba634219ae9c_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa

deploy:
  - provider: script
    script: 
      - scp -oStrictHostKeyChecking=no ./grey-jcr.tgz webeditor@greyjcr.com:./grey-jcr-new/ && ssh -oStrictHostKeyChecking=no -t webeditor@greyjcr.com < ./deploy.sh
    skip_cleanup: true
    on:
      branch: master

notifications:
  - email: false
